MODULE TestLTStructure;
   IMPORT SYSTEM;
    
   PROCEDURE PutChar(value: CHAR);
	  CONST
		 ACIA_DATA = 0C000H;
   BEGIN
      SYSTEM.PUT(ACIA_DATA, value);
   END PutChar;

   PROCEDURE TestLT(x, y: INTEGER; expected: BOOLEAN);
   BEGIN
      IF x < y THEN 
         PutChar('T')
      ELSE
         PutChar('F')
      END;
      IF expected THEN PutChar('Y') ELSE PutChar('N') END;
      PutChar(' ')
   END TestLT;

BEGIN
   PutChar('S');
   TestLT(10, -5, FALSE);    (* Should output "FN " *)
   TestLT(32767, -32768, FALSE); (* Should output "FN " *) 
   PutChar('E')
END TestLTStructure.