MODULE UIKit;
CONST
  (* Screen dimensions *)
  Width* = 640;
  Height* = 400;

  (* 16-color VGA palette *)
  Black* = 0;
  DarkBlue* = 1;
  DarkGreen* = 2;
  DarkCyan* = 3;
  DarkRed* = 4;
  DarkMagenta* = 5;
  Brown* = 6;
  LightGray* = 7;
  DarkGray* = 8;
  LightBlue* = 9;
  LightGreen* = 10;
  LightCyan* = 11;
  LightRed* = 12;
  LightMagenta* = 13;
  Yellow* = 14;
  White* = 15;
END UIKit.
