# Makefile
#
# Makefile for 65816 assembler

project = ln

include $(BUILD_BASE)/build/rules/global

objects = elf_file testELF

target = ln
target_version = 1

include $(BUILD_BASE)/build/rules/exec

