/* Definitions must be in alphabetical order */

DEF(ARRAY, "array")
DEF(BEGIN, "begin")
DEF(BY, "by")
DEF(CASE, "case")
DEF(CHAR, "char")
DEF(CONST, "const")
DEF(DIV, "div")
DEF(DO, "do")
DEF(ELSE, "else")
DEF(ELSIF, "elsif")
DEF(END, "end")
DEF(EXIT, "exit")
DEF(FALSE, "false")
DEF(FOR, "for")
DEF(IF, "if")
DEF(IMPORT, "import")
DEF(IN, "in")
DEF(IS, "is")
DEF(LOOP, "loop")
DEF(MOD, "mod")
DEF(MODULE, "module")
DEF(NIL, "nil")
DEF(OF, "of")
DEF(OR, "or")
DEF(POINTER, "pointer")
DEF(PROCEDURE, "procedure")
DEF(RECORD, "record")
DEF(REPEAT, "repeat")
DEF(RETURN, "return")
DEF(THEN, "then")
DEF(TO, "to")
DEF(TRUE, "true")
DEF(TYPE, "type")
DEF(UNTIL, "until")
DEF(VAR, "var")
DEF(WHILE, "while")
DEF(WITH, "with")

TOK(IDENT)
TOK(INTEGER)
TOK(REAL)
TOK(STRING)
TOK(PLUS)
TOK(MINUS)
TOK(AST)
TOK(SLASH)
TOK(TILDE)
TOK(AND)
TOK(PERIOD)
TOK(COMMA)
TOK(SEMICOLON)
TOK(BAR)
TOK(LPAREN)
TOK(RPAREN)
TOK(LSQ)
TOK(RSQ)
TOK(LBRACE)
TOK(RBRACE)
TOK(BECOMES)
TOK(CARET)
TOK(EQL)
TOK(NEQ)
TOK(LSS)
TOK(LEQ)
TOK(GTR)
TOK(GEQ)
TOK(DOTDOT)
TOK(COLON)
TOK(NULL)
TOK(EOF)
