# Makefile for Em16 - macOS standalone build (headless, no SDL)

CXX = c++
CXXFLAGS = -std=c++17 -Wall -Wextra -O2 -g -DNO_SDL -I./include -I./temp
LDFLAGS =

UNAME := $(shell uname -s)
ifeq ($(UNAME),Linux)
  LDFLAGS += -lutil
endif

SRCDIR = src
INCDIR = include
OBJDIR = obj
BINDIR = ../bin

SOURCES = emu816.cpp wdc816.cpp mem816.cpp UART_6551.cpp R6501.cpp Video.cpp memory.cpp main.cpp
OBJECTS = $(SOURCES:%.cpp=$(OBJDIR)/%.o)

TARGET = $(BINDIR)/em16

$(shell mkdir -p $(OBJDIR) $(BINDIR))

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

$(OBJDIR)/%.o: $(SRCDIR)/%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -rf $(OBJDIR) $(TARGET)

.PHONY: all clean
