# Makefile for Em16 - macOS build with Cocoa display support

CXX = c++
CXXFLAGS = -std=c++17 -Wall -Wextra -O2 -g -I./include -I./temp
LDFLAGS = -framework Cocoa

UNAME := $(shell uname -s)
ifeq ($(UNAME),Linux)
  LDFLAGS += -lutil
endif

SRCDIR = src
INCDIR = include
OBJDIR = obj
BINDIR = ../bin

CPP_SOURCES = emu816.cpp wdc816.cpp mem816.cpp UART_6551.cpp R6501.cpp memory.cpp main.cpp
MM_SOURCES = Video.mm

OBJECTS = $(CPP_SOURCES:%.cpp=$(OBJDIR)/%.o) $(MM_SOURCES:%.mm=$(OBJDIR)/%.o)

TARGET = $(BINDIR)/em16

$(shell mkdir -p $(OBJDIR) $(BINDIR))

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

$(OBJDIR)/%.o: $(SRCDIR)/%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(OBJDIR)/%.o: $(SRCDIR)/%.mm
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -rf $(OBJDIR) $(TARGET)

.PHONY: all clean
